server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/food_menu
      auto-index-creation: true
      uuid-representation: standard
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  jpa:
    show-sql: true
mongock:
  enabled: true
  migration-scan-package: com.foodapp.menu.db.changelog

api:
  base-path: /api/v1