services:
  postgres-order:
    image: postgres:16
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports: ["5432:5432"]
  postgres-payment:
    image: postgres:16
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports: ["5433:5432"]
  postgres-delivery:
    image: postgres:16
    environment:
      - POSTGRES_DB=deliverydb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports: ["5434:5432"]
  postgres-auth:
    image: postgres:16
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports: ["5435:5432"]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports: ["9092:9092"]
