server:
  port: 8087
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: app
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
