server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: app
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
kafka:
  bootstrap-servers: localhost:9092
