server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  cloud:
    gateway:
      routes: []
  data:
    redis:
      host: localhost
      port: 6379
