name: semantic-pr
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            perf
            docs
            test
            build
            ci
            chore
            revert
          scopes: |
            order-service
            menu-service
            cart-service
            payment-service
            delivery-service
            notification-service
            auth-service
            api-gateway
            repo
